AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs24.x
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
        Cors:
          AllowOrigins:
            - '*'
          AllowHeaders:
            - Content-Type
          AllowMethods:
            - POST
            - OPTIONS
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModelWithResponseStream
              Resource: '*'

Outputs:
  ChatFunctionUrl:
    Description: "Chat Function URL"
    Value: !GetAtt ChatFunctionUrl.FunctionUrl
